In [ ]:
import pandas as pd
import numpy as np

**Import data set**


In [15]:
dataset=pd.read_csv('D:\Machine Learning\Practice in ML\data.csv')

<>:1: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
<>:1: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
C:\Users\dell\AppData\Local\Temp\ipykernel_13372\3402671998.py:1: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
  dataset=pd.read_csv('D:\Machine Learning\Practice in ML\data.csv')


In [16]:
dataset

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No


Seperate Independent Variables


In [25]:
x=dataset[['Country','Age','Salary']].values

In [26]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0]], dtype=object)

Dependent Variable / Output


In [21]:
y=dataset[['Purchased']].values

In [22]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No']], dtype=object)

Want to remove the missing values form the x


In [28]:
from sklearn.impute import SimpleImputer

In [37]:
imputer=SimpleImputer(missing_values=np.nan, strategy="mean")

In [38]:
imputer=imputer.fit(x[:,1:3])

In [33]:
x[:,1:3]=imputer.transform(x[:,1:3])

In [34]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63375.0],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0]], dtype=object)

Convert Alphabatic data (country and Purchased) to the numeric data


In [ ]:
from sklearn.preprocessing import LabelEncoder

In [49]:
label_encoder_x = LabelEncoder()

In [ ]:
x[:,0] = label_encoder_x.fit_transform(x[:,0])

In [51]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63375.0],
       [0, 35.0, 58000.0],
       [2, 39.0, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0]], dtype=object)

In [67]:
from sklearn.preprocessing import OneHotEncoder

In [68]:
onehotencoder = OneHotEncoder()

In [69]:
x=onehotencoder.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()

In [70]:
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [85]:
labelencoder_y=LabelEncoder()

In [86]:
y = labelencoder_y.fit_transform(y)

In [87]:
y

array([1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0])

Trian and Test the model


In [92]:
from sklearn.model_selection import train_test_split

In [97]:
print("Shape of x:", getattr(x, 'shape', len(x)))
print("Shape of y:", getattr(y, 'shape', len(y)))

Shape of x: (9, 3)
Shape of y: (18,)


In [99]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

ValueError: Found input variables with inconsistent numbers of samples: [9, 18]