In [1]:
import pandas as pd
import numpy as np

**Import data set**


In [2]:
dataset=pd.read_csv('D:\Machine Learning\Practice in ML\Preprocessing_dataset.csv')

<>:1: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
<>:1: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
C:\Users\dell\AppData\Local\Temp\ipykernel_10536\1347726640.py:1: SyntaxWarning: "\M" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\M"? A raw string is also an option.
  dataset=pd.read_csv('D:\Machine Learning\Practice in ML\Preprocessing_dataset.csv')


In [3]:
dataset

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No


Seperate Independent Variables


In [4]:
x=dataset[['Country','Age','Salary']].values

In [5]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0]], dtype=object)

Dependent Variable / Output


In [6]:
y=dataset[['Purchased']].values

In [7]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No']], dtype=object)

Want to remove the missing values form the x


In [8]:
from sklearn.impute import SimpleImputer

In [9]:
imputer=SimpleImputer(missing_values=np.nan, strategy="mean")

In [10]:
imputer=imputer.fit(x[:,1:3])

In [11]:
x[:,1:3]=imputer.transform(x[:,1:3])

In [12]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63375.0],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0]], dtype=object)

Convert Alphabatic data (country and Purchased) to the numeric data


In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
label_encoder_x = LabelEncoder()

In [15]:
x[:,0] = label_encoder_x.fit_transform(x[:,0])

In [16]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63375.0],
       [0, 35.0, 58000.0],
       [2, 39.0, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0]], dtype=object)

In [17]:
from sklearn.preprocessing import OneHotEncoder

In [18]:
onehotencoder = OneHotEncoder()

In [19]:
x=onehotencoder.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()

In [20]:
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [21]:
labelencoder_y=LabelEncoder()

In [22]:
y = labelencoder_y.fit_transform(y)

c:\Users\dell\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [23]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0])

Trian and Test the model


In [24]:
from sklearn.model_selection import train_test_split

In [25]:
print("Shape of x:", getattr(x, 'shape', len(x)))
print("Shape of y:", getattr(y, 'shape', len(y)))

Shape of x: (9, 3)
Shape of y: (9,)


In [26]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [27]:
x_train

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [28]:
x_test

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
y_train

array([1, 0, 0, 0, 0, 1])

In [30]:
y_test

array([1, 0, 1])

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
sc_x=StandardScaler()

In [33]:
x_train=sc_x.fit_transform(x_train)

In [34]:
x_test=sc_x.transform(x_test)

In [35]:
x_train

array([[-0.70710678,  1.41421356, -0.70710678],
       [-0.70710678,  1.41421356, -0.70710678],
       [-0.70710678, -0.70710678,  1.41421356],
       [-0.70710678, -0.70710678,  1.41421356],
       [ 1.41421356, -0.70710678, -0.70710678],
       [ 1.41421356, -0.70710678, -0.70710678]])

In [36]:
x_test

array([[ 1.41421356, -0.70710678, -0.70710678],
       [-0.70710678,  1.41421356, -0.70710678],
       [-0.70710678, -0.70710678,  1.41421356]])

Thanks
